web-eid/web-eid-app

src/controller/command-handlers/certificatereader.cpp
Disconnect signals before connecting in command handler base class `CertificateReader::connectSignals()`.
Refs WE2-115
=> fix(error-handling): disconnect signals before connecting 

src/controller/threads/readermonitorthread.hpp
=> std::vector does not contain null char at end and fix log output

src/controller/controller.cpp, src/controller/retriableerror.cpp, src/controller/retriableerror.hpp
Refs WE2-472
Signed-off-by: Mart Somermaa <mrts@users.noreply.github.com>
=> refactor(RetriableError): remove ScardError from AutoSelectFailed and handle it directly in CATCH_PCSC_CPP_RETRIABLE_ERRORS

CMakeLists.txt, src/mac/CMakeLists.txt, src/mac/web-eid-safari.entitlements
This reverts commit f342c4026cd429164ddc4efc8c4537842d8366a1.
=> Revert "Add missing entitlements keys and include provisionprofile"

install/web-eid.desktop
The Encoding key is deprecated.
Ref: https://specifications.freedesktop.org/desktop-entry-spec/latest/apc.html
```sh
$ cat /usr/share/applications/web-eid.desktop
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=web-eid %F
Icon=web-eid
Name=Web eID
Categories=Qt;Office;
$ desktop-file-validate /usr/share/applications/web-eid.desktop
/usr/share/applications/web-eid.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
```
=> Remove deprecated key in desktop entry

debian/rules, src/app/CMakeLists.txt
The official Debian package includes this file, but other systems do not
neccessarily need it;  at least OpenBSD is unable to download files from
the intenet during packaging, so this fails ether way.
Allow for `-DBUNDLE_XPI=OFF` to skip it.`
=> Linux, BSD: Add BUNDLE_XPI option

install/web-eid.desktop, src/controller/application.cpp
=> Add separate about command for about

src/controller/application.cpp
Signed-off-by: Mart Somermaa <mrts@users.noreply.github.com>
=> fix: restore the --parent-window option

.github/workflows/cmake-macos.yml
=> Build universal binaries

src/controller/application.cpp
Web-eID app supports dark theme, but this is disabled on linux:
> Disabled as there is currently no straightforward way to detect dark mode in Linux.
Agreed, this is not straightforward, but can be made work with some configurations. Updated code to use check `gsettings get org.gnome.desktop.interface color-scheme` instead, as this [specifies the preferred color scheme for the user interface](https://github.com/GNOME/gsettings-desktop-schemas/blob/3e998989a292bff6ac6415b7f1d5c91d4e80e6f6/schemas/org.gnome.desktop.interface.gschema.xml.in#L297).
=> Enable dark theme

.github/workflows/cmake-linux-codeql.yml, .github/workflows/cmake-linux-coverity.yml, .github/workflows/cmake-linux-fedora.yml, .github/workflows/cmake-linux-ubuntu.yml, .github/workflows/cmake-macos.yml, .github/workflows/cmake-windows.yml
=> Merge libpcsc-cpp and libpcsc-mock repositories

src/ui/dialog.ui, src/ui/webeiddialog.cpp
=> Split menu to two rows and workaround character truncation

src/controller/application.cpp, src/controller/application.mm, src/controller/threads/commandhandlerconfirmthread.hpp, src/controller/threads/commandhandlerrunthread.hpp, src/ui/certificatewidget.cpp, src/ui/webeiddialog.cpp
- keep linux compatibility
WE2-826
=> Use Qt 6.5 styleHint colorScheme to detect dark theme

src/controller/command-handlers/authenticate.cpp, src/controller/command-handlers/sign.cpp, src/controller/command-handlers/signauthutils.cpp, src/controller/command-handlers/signauthutils.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Workaround when reading card delays and use presses sign again

.github/workflows/cmake-linux-fedora.yml, debian/not-installed, debian/web-eid-chrome.install, src/app/CMakeLists.txt
=> Add chromium support

src/controller/CMakeLists.txt, src/controller/command-handlers/authenticate.cpp, src/controller/command-handlers/sign.cpp, src/controller/command-handlers/signauthutils.cpp, src/controller/command-handlers/signauthutils.hpp, src/controller/controller.cpp, src/controller/inputoutputmode.cpp, src/controller/utils/erasedata.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
WE2-479
Signed-off-by: Lauris Kaplinski <lauris@raulwalter.com>
=> Resolve fixme-s in code

src/controller/controller.cpp, src/ui/webeiddialog.cpp
WE2-479
Signed-off-by: Lauris Kaplinski <lauris.kaplinski@raulwalter.com>
=> Fix invalid argument error in stdin mode

.github/workflows/cmake-linux-fedora.yml, .github/workflows/cmake-linux-ubuntu.yml, src/app/main.cpp, src/controller/inputoutputmode.cpp, src/controller/writeresponse.cpp, src/mac/main.mm
=> Make Reader simple struct

src/controller/application.cpp, src/controller/certandpininfo.hpp, src/controller/command-handlers/authenticate.cpp, src/controller/command-handlers/authenticate.hpp, src/controller/command-handlers/certificatereader.cpp, src/controller/command-handlers/certificatereader.hpp, src/controller/command-handlers/getcertificate.cpp, src/controller/command-handlers/getcertificate.hpp, src/controller/command-handlers/sign.cpp, src/controller/command-handlers/sign.hpp, src/controller/commandhandler.hpp, src/controller/controller.cpp, src/controller/controller.hpp, src/controller/qeid.hpp, src/controller/threads/cardeventmonitorthread.hpp, src/controller/threads/commandhandlerconfirmthread.hpp, src/controller/threads/commandhandlerrunthread.hpp, src/controller/threads/waitforcardthread.hpp, src/controller/ui.hpp, src/ui/certificatewidget.cpp, src/ui/certificatewidget.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp, tests/mock-ui/mock-ui.hpp, tests/tests/changecertificatevaliduntil.hpp, tests/tests/main.cpp
=> Remove CardInfo and add EstEID Thales support

src/controller/controller.cpp, src/controller/controller.hpp, src/controller/threads/cardeventmonitorthread.hpp, src/controller/threads/commandhandlerconfirmthread.hpp, src/controller/threads/commandhandlerrunthread.hpp, src/controller/threads/controllerchildthread.hpp, src/controller/threads/waitforcardthread.hpp, src/controller/ui.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp, tests/mock-ui/mock-ui.cpp
=> Cleanup thread cleaning and fix PinPAD crash
