web-eid/web-eid-app

.github/workflows/cmake-macos.yml
=> Use OpenSSL 1.1

CMakeLists.txt, src/app/CMakeLists.txt
=> Add option to sign macOS and Windows binaries

debian/postinst
=> build: fix extension install URL in Debian package postinst script

.github/workflows/cmake-windows.yml, README.md, install/WelcomeDlg2.wxs, install/WixUI_Minimal2.wxs, install/web-eid.wxs, src/app/CMakeLists.txt
=> Add WIX UI

src/controller/command-handlers/authenticate.cpp, src/controller/command-handlers/authenticate.hpp, src/controller/command-handlers/certificatereader.cpp, src/controller/command-handlers/certificatereader.hpp, src/controller/command-handlers/sign.cpp, src/controller/command-handlers/sign.hpp, src/controller/command-handlers/signauthutils.cpp, src/controller/command-handlers/signauthutils.hpp, src/controller/commandhandler.hpp, src/controller/ui.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp, tests/mock-ui/mock-ui.cpp, tests/mock-ui/mock-ui.hpp, tests/tests/main.cpp
=> fix: make PIN access from background threads safe

README.md
=> doc: amend Windows build instructions

.github/workflows/cmake-macos.yml, src/mac/CMakeLists.txt
=> Include Safari installer

src/controller/command-handlers/authenticate.cpp, src/controller/command-handlers/sign.cpp
=> When PIN is blocked, it is not retry error

.github/workflows/cmake-macos.yml, src/app/CMakeLists.txt, src/mac/CMakeLists.txt
=> Split macOS components to separate installers

src/mac/main.mm, src/mac/safari-extension.mm
=> Check if dictionary contains nonce

src/controller/logging.cpp
=> Setting to enable logging to file

src/controller/command-handlers/authenticate.cpp
=> refactor(authenticate): Use currentDateTimeUtc().toSecsSinceEpoch() in iat and exp fields

.github/workflows/cmake-linux-ubuntu.yml, src/controller/certificateinfo.hpp
=> Include debug symbols and fix build with gcc

.github/workflows/cmake-linux-ubuntu.yml, debian/control, debian/copyright, debian/rules, src/app/CMakeLists.txt
=> Fix debian license format and optimize build

.github/workflows/cmake-linux-ubuntu.yml
=> Include debian artifacts

src/ui/certificatelistwidget.cpp
=> fix(multi-card): don't hide data member in CertificateListWidget::selectedCertificate()

src/ui/certificatelistwidget.cpp, src/ui/dialog.ui, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> PinPAD fixes

src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Improve UI PIN error messages

.github/workflows/cmake-windows.yml, install/web-eid.wxs, src/app/CMakeLists.txt
=> Make Windows installer configurable

install/web-eid.wxs
=> Include qsvg.dll plugin

src/mac/CMakeLists.txt
=> Fix macOS codesigning

src/ui/dialog.ui, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Merge screens and cleanup code

debian/source/format, src/app/CMakeLists.txt, src/app/main.cpp, src/controller/CMakeLists.txt, src/controller/application.cpp, src/controller/application.hpp, src/mac/main.mm, src/mac/safari-extension.mm, tests/tests/main.cpp
=> Merge common code to Application class

README.md, src/ui/certificatelistwidget.cpp, src/ui/certificatelistwidget.hpp, src/ui/dialog.ui, src/ui/translations/en.ts, src/ui/translations/et.ts, src/ui/translations/fi.ts, src/ui/translations/ru.ts, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Subclass QListWidget directly

src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Disable OK/Cancel buttons when signing is in progress

src/controller/command-handlers/authenticate.cpp
=> Use GN and SN when available

src/controller/controller.cpp, src/controller/controller.hpp
=> Clear all libelectronic-id handles before retry

src/ui/certificatelistwidget.cpp, src/ui/certificatelistwidget.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Fix enabled OK button and cleanup make flow readable

build.sh, src/controller/CMakeLists.txt, src/controller/command-handlers/certificatereader.hpp, src/controller/commandhandler.hpp, src/controller/controller.cpp, src/controller/controller.hpp, src/controller/threads/cardeventmonitorthread.hpp, src/controller/threads/controllerchildthread.cpp, src/controller/threads/controllerchildthread.hpp, src/controller/threads/waitforcardthread.hpp
=> feat: add card event monitor thread

src/ui/certificatelistwidget.cpp, src/ui/certificatelistwidget.hpp
=> Revert, fix build

src/ui/webeiddialog.cpp
=> Fix PIN input dialog labels

src/ui/translations/en.ts, src/ui/translations/et.ts, src/ui/translations/fi.ts, src/ui/translations/ru.ts, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Disable OK button on pin retry and hide on pin blocked

src/controller/controller.cpp, src/controller/ui.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp, tests/mock-ui/mock-ui.cpp
=> fix(ui): show waiting for card page by default

src/mac/main.mm
=> Catch critical error

README.md
=> doc: update README with recent changes

src/mac/main.mm
=> fix(safari): return error response from notification event handler

debian/control, debian/rules, debian/web-eid.postinst, debian/web-eid.postrm, install/web-eid.wxs, src/app/CMakeLists.txt, src/mac/Info-app.plist.cmake, src/mac/Info-extension.plist.cmake
=> macOS signing fixes and other packaging fixes

src/controller/commands.cpp, src/controller/commands.hpp, src/controller/controller.cpp, tests/input-output-mode/test.py, tests/tests/main.cpp
=> feat: add new command "quit" for extension

src/app/CMakeLists.txt, src/mac/CMakeLists.txt, src/mac/web-eid-safari-extension.entitlements, src/mac/web-eid-safari.entitlements
=> Fix domain and enable hardened signing

README.md, src/app/getcommandhandler.cpp, src/controller/application.cpp, src/controller/command-handlers/certificatereader.cpp, src/controller/command-handlers/getcertificate.cpp, src/controller/commands.cpp, src/controller/commands.hpp, src/ui/webeiddialog.cpp, tests/input-output-mode/test.py, tests/tests/getcommandhandler-mock.cpp, tests/tests/main.cpp
=> Remove access to authentication certificate

src/ui/dialog.ui, src/ui/webeiddialog.cpp
=> Improve tab order

src/ui/webeiddialog.cpp
=> Fix tab order

install/HyperlinkSidebarTheme.en.wxl, install/HyperlinkSidebarTheme.et.wxl
=> Remove changelog link and clean SuccessInstallMessage

src/controller/threads/controllerchildthread.hpp, src/ui/webeiddialog.cpp
=> fix(pin-input): display PIN blocked error, not fatal error when PIN gets blocked

install/HyperlinkSidebarTheme.en.wxl, install/HyperlinkSidebarTheme.et.wxl
=> Set Changelog link to empty string

src/ui/translations/en.ts
WE2-358
Signed-off-by: Kristel Merilain <kristel.merilain@ria.ee>
=> Fix url in translation

install/plugins.wxs
=> Install X64 to X64 ProgramFiles folder

install/HyperlinkSidebarTheme.xml, install/plugins.wxs, install/web-eid.wxs
=> Add Install options

install/HyperlinkSidebarTheme.xml, install/web-eid.wxs
=> Add installer Modify options

src/ui/webeiddialog.cpp
=> Select certificate when there is one

src/app/CMakeLists.txt, src/app/MacOSXBundleInfo.plist.in, src/app/web-eid.entitlements, src/mac/CMakeLists.txt, src/mac/Info-app.plist.cmake, src/mac/main.mm, src/mac/safari-extension.mm, src/mac/shared.hpp, src/ui/dialog.ui, src/ui/translations/en.ts, src/ui/translations/et.ts, src/ui/translations/fi.ts, src/ui/translations/ru.ts, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Show about dialog

src/controller/application.cpp, src/controller/commands.hpp, src/controller/controller.cpp, src/controller/controller.hpp, src/controller/ui.hpp, src/ui/ui.cpp, tests/mock-ui/mock-ui.cpp
=> Web eID about

src/mac/safari-extension.mm
=> Remove key when application failed to start

src/app/CMakeLists.txt, src/app/InfoPlist.strings, src/app/MacOSXBundleInfo.plist.in, src/mac/CMakeLists.txt, src/mac/Info-app.plist.cmake, src/mac/InfoPlist.strings, src/ui/webeiddialog.cpp
=> Set pretty application name under macOS

src/app/main.cpp, src/controller/application.cpp, src/controller/application.hpp, src/mac/Info-extension.plist.cmake, src/mac/InfoPlist.strings, src/mac/main.mm
=> Remove Safari from display name

.github/workflows/cmake-windows.yml, tests/input-output-mode/test.py
=> fix(tests): add --parent-window=unused to Popen() in input-output-mode/test.py to avoid popping up About dialog

src/ui/webeiddialog.cpp
=> Revert this change

src/controller/application.hpp, src/mac/main.mm, src/ui/dialog.ui, src/ui/images/fatal.svg, src/ui/translations/en.ts, src/ui/translations/et.ts, src/ui/translations/fi.ts, src/ui/translations/ru.ts, src/ui/web-eid-resources.qrc, src/ui/webeiddialog.cpp
=> Update about dialog

src/controller/CMakeLists.txt, src/controller/application.cpp, src/controller/controller.cpp, src/controller/controller.hpp, src/controller/observer_ptr.hpp, src/controller/ui.hpp, src/ui/ui.cpp, src/ui/webeiddialog.cpp, tests/mock-ui/mock-ui.cpp
=> Avoid crash when cancel is pressed

src/controller/application.cpp, src/mac/main.mm, src/mac/safari-extension.mm
=> fix(safari): fix WebEidStarting check and add logging to web-eid-safari app

src/mac/safari-extension.mm
=> Optimize, response version number from extension

src/ui/translations/et.ts
WE2-603
Signed-off-by: Kristel Merilain <kristel.merilain@ria.ee>
=> Update et translation

.github/workflows/cmake-linux-ubuntu.yml, src/mac/safari-extension.mm
=> Fix version number

src/mac/Info-app.plist.cmake
=> Set default option for App Store

src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Hide warning when user is typing

src/mac/CMakeLists.txt
=> feat(macos): update extension JavaScript with v2 changes

.github/workflows/cmake-windows.yml, install/web-eid.wxs, src/controller/application.hpp
=> Fix build with VS 2022 and use VC 2019 in CI

install/HyperlinkSidebarTheme.en.wxl, install/HyperlinkSidebarTheme.et.wxl, install/HyperlinkSidebarTheme.xml, install/distribution.xml
=> Update installer texts

README.md
=> docs: update README, describe internal design and Safari extension, amend wording

src/ui/translations/fi.ts, tests/input-output-mode/test.py
=> feat(translations): add Finnish translations

src/ui/translations/en.ts, src/ui/translations/et.ts, src/ui/translations/fi.ts, src/ui/translations/ru.ts, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Allow to move back when case authentication and multiple certificates

CMakeLists.txt, src/mac/CMakeLists.txt, src/mac/web-eid-safari.entitlements
=> Add missing entitlements keys and include provisionprofile

src/app/web-eid.entitlements
=> Add sandbox exception for dload module

src/ui/webeiddialog.cpp
=> Remove hover when window is changed

.github/workflows/cmake-macos.yml, src/controller/CMakeLists.txt, src/controller/application.cpp, src/controller/application.hpp, src/controller/application.mm, src/mac/CMakeLists.txt, src/ui/webeiddialog.cpp
=> Add About to macOS menubar

src/controller/command-handlers/sign.cpp, src/controller/command-handlers/sign.hpp, src/controller/command-handlers/signauthutils.cpp, src/controller/command-handlers/signauthutils.hpp, src/controller/ui.hpp, src/ui/translations/en.ts, src/ui/translations/et.ts, src/ui/translations/fi.ts, src/ui/translations/ru.ts, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp, tests/mock-ui/mock-ui.hpp
=> Don't parse untrusted input

src/ui/dialog.ui, src/ui/images/left.svg, src/ui/web-eid-resources.qrc, src/ui/webeiddialog.cpp
=> Use separate button for certificate selection

README.md, src/ui/translations/hr.ts, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> feat(eid): add Croatian eID support

install/idemiaawppkcs11-mac.json, install/idemiaawppkcs11-win.json, install/onepinopenscpkcs11-mac.json, install/onepinopenscpkcs11-win.json, install/web-eid.wxs, src/app/CMakeLists.txt
=> Remove PKCS11 module from Firefox

.github/workflows/cmake-macos.yml, .github/workflows/cmake-windows.yml, CMakeLists.txt, README.md, build.sh, install/web-eid.wxs, src/app/CMakeLists.txt, src/controller/CMakeLists.txt, src/controller/application.cpp, src/controller/certandpininfo.hpp, src/controller/controller.cpp, src/mac/CMakeLists.txt, src/ui/CMakeLists.txt, src/ui/certificatewidget.cpp, src/ui/ui.cpp, test.sh, tests/input-output-mode/test.py, tests/mock-ui/mock-ui.hpp, tests/tests/CMakeLists.txt, tests/tests/main.cpp
=> Add Qt6 support

src/controller/controller.cpp, src/controller/controller.hpp, src/controller/ui.hpp, src/ui/webeiddialog.hpp, tests/mock-ui/mock-ui.hpp
=> Fix PIN pad window closing in Qt 6

src/ui/webeiddialog.cpp
=> fix(ui): redirect stdout to pipe before QDesktopServices::openUrl() to avoid ruining the browser-app communication channel

src/controller/command-handlers/authenticate.cpp, src/controller/command-handlers/sign.cpp
=> Use correct error code

install/idemiaawppkcs11-mac.json, install/idemiaawppkcs11-win.json, install/onepinopenscpkcs11-mac.json, install/onepinopenscpkcs11-win.json, install/web-eid.wxs, src/app/CMakeLists.txt
This reverts commit 4118e4cde6d02d72b8983316d3c9d57f263548a7.
=> Revert "Remove PKCS11 module from Firefox"

.github/workflows/cmake-windows.yml, install/plugins.wxs, src/app/CMakeLists.txt
=> Build only Burn installer with single arch

src/app/CMakeLists.txt
=> Select correct certificate for package signing

debian/web-eid-firefox.install, src/app/CMakeLists.txt
=> Bundle XPI extension in DEB package

.github/workflows/cmake-macos.yml, .github/workflows/cmake-windows.yml, install/web-eid.wxs
=> Use OpenSSL 3.0

.github/workflows/cmake-linux-ubuntu.yml, debian/control
=> Build on ubuntu Qt 5 and 6

src/controller/retriableerror.hpp, src/controller/threads/waitforcardthread.hpp, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Fix PIN prompt on another certificate selection

.github/workflows/cmake-linux-fedora.yml
=> Fix Fedora native binary path

src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Hide select another certificate on signature screen

.github/workflows/cmake-linux-ubuntu.yml
=> Fix Coverity build

install/web-eid.wxs
=> WIP: Block token signing Chrome/Edge extensions

src/ui/webeiddialog.cpp
=> Accept return and enter key press from QLineEdit

.github/workflows/cmake-macos.yml, .github/workflows/cmake-windows.yml
=> Update GitHub Actions tasks

src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Set other certificate selection visible only when needed

.gitignore, src/controller/command-handlers/certificatereader.cpp, src/controller/command-handlers/sign.cpp, src/controller/inputoutputmode.cpp, src/controller/utils.hpp, src/ui/translations/en.ts, src/ui/translations/et.ts, src/ui/translations/fi.ts, src/ui/translations/hr.ts, src/ui/translations/ru.ts, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> feat(cards): add support for MS CryptoAPI tokens

src/ui/webeiddialog.cpp
=> Disable icon on linux

src/controller/command-handlers/certificatereader.cpp, tests/tests/main.cpp
=> Format subject info

src/controller/command-handlers/certificatereader.cpp
=> Format name only when SN ang GN are available

src/ui/dialog.ui, src/ui/translations/de.ts, src/ui/translations/fr.ts, src/ui/translations/nl.ts, src/ui/webeiddialog.cpp
=> Adjust translations

src/controller/command-handlers/certificatereader.cpp, src/ui/ui.cpp, src/ui/webeiddialog.cpp
=> Fix coverity warnings

src/ui/translations/de.ts, src/ui/translations/fr.ts, src/ui/translations/nl.ts
=> Update DE, FR, NL translations

src/ui/certificatewidget.cpp, src/ui/dialog.ui, src/ui/translations/fr.ts
=> Use word wrap

install/HyperlinkSidebarTheme.cs.wxl, install/HyperlinkSidebarTheme.sk.wxl, install/cs.lproj/Conclusion.html, install/cs.lproj/Localizable.strings, install/cs.lproj/Welcome.html, install/plugins.wxs, install/sk.lproj/Conclusion.html, install/sk.lproj/Localizable.strings, install/sk.lproj/Welcome.html, src/controller/application.cpp, src/ui/CMakeLists.txt, src/ui/translations/cs.ts, src/ui/translations/sk.ts, src/ui/translations/translations.qrc, src/ui/webeiddialog.cpp
Signed-off-by: Martin Mayer <martin.kelly.mayer@gmail.com>
=> CZ and SK localization

src/ui/translations/cs.ts, src/ui/translations/sk.ts
=> Fix plural forms

.github/workflows/cmake-macos.yml, .github/workflows/cmake-windows.yml, CMakeLists.txt, build.ps1, build.sh
=> Use official QT binaries

.github/workflows/cmake-macos.yml
=> Cache dependencies

.github/workflows/cmake-linux-fedora.yml
#302, WE2-842
Signed-off-by: Lauris Kaplinski <laurius@raulwalter.com>
=> Updated Fedora versions

src/app/CMakeLists.txt, tests/mock-ui/mock-ui.hpp, tests/tests/main.cpp
=> Remove Gemalto card support

src/controller/command-handlers/authenticate.cpp
=> Add SHA256 and SHA512 to supported ECC hash algorithms

src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Optimize: use const char* where possible

src/controller/command-handlers/certificatereader.cpp, src/ui/certificatewidget.cpp, src/ui/certificatewidget.hpp
=> HTML escape certificate fields

src/controller/controller.cpp
WE2-556
Signed-off-by: Mart Somermaa <mrts@users.noreply.github.com>
=> Omit exception message from JSON output

.github/workflows/cmake-linux-codeql.yml, src/controller/command-handlers/signauthutils.hpp, src/controller/controller.cpp, tests/tests/changecertificatevaliduntil.hpp
=> Fix CodeQL warnings

.github/workflows/cmake-windows.yml, install/web-eid.wxs
=> Update Qt 6.7.1

.github/workflows/cmake-linux-ubuntu.yml, debian/control, debian/source/options
=> Update deb source pacakge ignore list and add package suggestions

src/ui/dialog.ui, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Use fixed size layout constraint

src/ui/webeiddialog.cpp
=> Fix layout with all languages

.github/workflows/cmake-macos.yml, .github/workflows/cmake-windows.yml, install/English.lproj/Localizable.strings, install/cs.lproj/Localizable.strings, install/distribution.xml, install/et.lproj/Localizable.strings, install/ru.lproj/Localizable.strings, install/sk.lproj/Localizable.strings
=> Set macOS minimum target 12.0

src/controller/threads/commandhandlerconfirmthread.hpp
WE2-911
Signed-off-by: Mart Somermaa <mrts@users.noreply.github.com>
=> Add Pkcs11ElectronicID::release()

src/ui/dialog.ui, src/ui/webeiddialog.cpp, src/ui/webeiddialog.hpp
=> Revert change f2374c245bcc64f74f8a05ee864ce1e64f1eb098

debian/control, install/eu.webeid.chrome-policy.json
=> Add qt6-qpa-plugins dependency

.github/workflows/cmake-windows.yml, src/app/CMakeLists.txt
=> Update code signature timestamping URL-s

src/controller/command-handlers/authenticate.cpp, src/controller/command-handlers/sign.cpp
=> Take PIN ownership to minimze memory copy-s
